BookWeb/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls import url, handler404, handler400, handler403, handler500
from django.conf import settings
from django.views.static import serve

path_to_error = 'books.views.error_4xx'

handler404 = path_to_error
handler400 = path_to_error
handler403 = path_to_error
handler500 = 'books.views.error_500'

urlpatterns = [
    path('', include('books.urls')),
    path('panel-administratora/', admin.site.urls, name='admin_panel'),
    # path('panel-administratora/doc/', include('django.contrib.admindocs.urls')),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
           'document_root': settings.MEDIA_ROOT,
        }),
    ]

books/urls.py
from django.urls import path

from . import views
from books.views import IndexBooksView, BookView, AuthorsView, AuthorView

app_name = 'books'
urlpatterns = [
    path('ksiazki/', IndexBooksView.as_view(), name='index'),
    path('autorzy/', AuthorsView.as_view(), name='authors'),
    path('szukaj/', views.search, name='search'),
    path('ksiazka/<book_id>/', BookView.as_view(), name='book'),
    path('autor/<author_id>', AuthorView.as_view(), name='book_author'),
    path('kategoria/<category_id>', views.category, name='book_category'),
    path('<book_id>/dodaj-komentarz', views.book_add_comment, name='book_add_comment'),
    path('<book_id>/plus', views.vote_plus, name='book_plus'),
    path('<book_id>/minus', views.vote_minus, name='book_minus'),
    path('zaloguj-sie', views.log_in, name='login'),
    path('wyloguj-sie', views.log_out, name='logout'),
    path('zajerestruj-sie', views.register_user, name='register_user'),

]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
import sys
from io import BytesIO
from django.core.files.uploadedfile import InMemoryUploadedFile
# from django.utils.html import format_html
# from django.urls import reverse


# Create your models here.

class Author(models.Model):
    name = models.CharField("Autor", max_length=50)
    description = models.TextField("Opis autora", max_length=None, default="Brak opisu")

    class Meta:
        verbose_name = 'Autor'
        verbose_name_plural = 'Autorzy'

    def __str__(self):
        return self.name


class Category(models.Model):
    category_name = models.CharField("Kategoria", max_length=50)

    class Meta:
        verbose_name = 'Kategoria'
        verbose_name_plural = 'Kategorie'

    def __str__(self):
        return self.category_name


class Book(models.Model):
    book_title = models.CharField("Tytuł książki", max_length=50)
    book_desc = models.TextField("Opis książki", max_length=None)
    book_width = models.PositiveIntegerField("Szerokość okładki (w px)", default="200")
    book_height = models.PositiveIntegerField("Wysokość okładki (w px)", default="400")
    book_img = models.ImageField("Okładka książki", width_field='book_width', height_field='book_height', blank=True,
                                 null=True, upload_to="covers/%Y/%m/%D/")
    book_author = models.ManyToManyField(Author, verbose_name="Autor/Autorzy")
    book_category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategoria")
    pub_date = models.DateTimeField('Data utworzenia', auto_now_add=True)

    book_rate = models.IntegerField("Ocena książki(%)", null=True)

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        # Opening the uploaded image
        try:
            im = Image.open(self.book_img).convert('RGB')

            output = BytesIO()

            im_resize = im.resize((350, 490))

            # Resize/modify the image
            im = im_resize

            # after modifications, save it to the output
            im.save(output, format='JPEG', quality=100)
            output.seek(0)

            # change the imagefield value to be the newley modifed image value
            self.book_img = InMemoryUploadedFile(output, 'ImageField', "%s.jpg" % self.book_img.name.split('.')[0],
                                                 'image/jpeg', sys.getsizeof(output), None)

            super(Book, self).save()
        except ValueError:
            super(Book, self).save()

    class Meta:
        verbose_name = 'Książkę'
        verbose_name_plural = 'Książki'

    def __str__(self):
        return self.book_title


class Comment(models.Model):
    content = models.TextField("Treść komentarza", max_length=500)
    user = models.ForeignKey(User, verbose_name="Użytkownik", on_delete=models.CASCADE, default=None, blank=True)
    pub_date = models.DateTimeField('Data utworzenia', auto_now_add=True)
    book = models.ForeignKey(Book, verbose_name="Książka", on_delete=models.CASCADE, default=None, blank=True)

    class Meta:
        verbose_name = 'Komentarz'
        verbose_name_plural = 'Komentarze'

    def __str__(self):
        return self.content[:10]


class Rating(models.Model):
    like = models.BooleanField("Like")
    dislike = models.BooleanField("Dislike")
    user = models.ForeignKey(User, verbose_name="Użytkownik", on_delete=models.CASCADE, default=None, blank=True)
    book = models.ForeignKey(Book, verbose_name="Książka", on_delete=models.CASCADE, default=None, blank=True)

    class Meta:
        verbose_name = 'Ocena'
        verbose_name_plural = 'Oceny'

    def __str__(self):
        return "Ocena dla: " + self.book.book_title

books/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import View
from django.db.models import Q
import matplotlib.pyplot as plt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
import json
from django.core.paginator import Paginator

from django.template import loader

from .models import *


def error_4xx(request, exception):
    return render(request, 'error.html')


def error_500(request):
    return render(request, 'error.html')


class IndexBooksView(View):
    def get(self, request, *args, **kwargs):
        books = Book.objects.order_by('-pub_date')

        context = {
            'books': books,
        }
        return render(request, 'books/index.html', context)


class BookView(View):
    def get(self, request, book_id, *args, **kwargs):
        book = get_object_or_404(Book, pk=book_id)
        comments = Comment.objects.filter(book_id=book_id).order_by('-pub_date')
        paginator = Paginator(comments, 10)
        page_number = request.GET.get('strona')
        page_obj = paginator.get_page(page_number)
        title = book.book_title
        votes = book.rating_set.count()
        likes = Rating.objects.filter(book=book, like=True).count()
        if votes > 0:
            rate = (likes / votes) * 100
        else:
            rate = 0
        liked = False
        disliked = False
        if request.user.is_authenticated:
            user = request.user
            try:
                Rating.objects.get(user=user, book=book, like=True)
                liked = True
            except Rating.DoesNotExist:
                liked = False
            try:
                Rating.objects.get(user=user, book=book, dislike=True)
                disliked = True
            except Rating.DoesNotExist:
                disliked = False
        return render(request, 'books/book.html', {
            'book': book,
            'title': title,
            'comments': comments,
            'request': request,
            'votes': votes,
            'rate': round(rate),
            'liked': liked,
            'disliked': disliked,
            'page_obj': page_obj
        })


class AuthorsView(View):

    def get(self, request, *args, **kwargs):
        authors = Author.objects.all()
        context = {
            'authors': authors,
        }
        return render(request, 'authors/authors.html', context)


class AuthorView(View):
    def get(self, request, author_id, *args, **kwargs):
        author = get_object_or_404(Author, pk=author_id)

        context = {
            'author': author
        }
        return render(request, 'authors/author.html', context)


def log_in(request):
    if request.is_ajax() and request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        response_data = {}
        if user is not None:
            login(request, user)
            response_data['result'] = 'success'
        else:
            response_data['result'] = 'failed'
        return HttpResponse(json.dumps(response_data), content_type="application/json")


def register_user(request):
    if request.is_ajax() and request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_repeat = request.POST['password_repeat']
        email = request.POST['email']
        response_data = {}
        if password != password_repeat:
            response_data['result'] = 'failed'
        else:
            group = Group.objects.get(name='user')
            try:
                user = User.objects.get(username=username)
                response_data['result'] = 'username_exist'
            except User.DoesNotExist:
                try:
                    user = User.objects.get(email=email)
                    response_data['result'] = 'email_exist'
                except User.DoesNotExist:
                    user = User.objects.create_user(
                        username=username,
                        email=email,
                        password=password,
                    )
                    user.groups.add(group)
                    user.save()
                    login(request, user)
                    response_data['result'] = 'success'
        return HttpResponse(json.dumps(response_data), content_type="application/json")


def log_out(request):
    logout(request)
    return HttpResponse('')


def book_add_comment(request, book_id):
    if request.is_ajax() and request.method == 'POST':
        user = get_object_or_404(User, pk=request.POST['user_id'])
        content = request.POST['content']
        book = get_object_or_404(Book, pk=book_id)
        comment = Comment(user=user, content=content, book=book)
        comment.save()
        return HttpResponse('')


def vote_plus(request, book_id):
    if request.is_ajax() and request.method == 'POST':
        book = get_object_or_404(Book, pk=book_id)
        user = request.user
        response_data = {}
        update_book_rating(book)
        try:
            rating = Rating.objects.get(
                user=user,
                book=book,
                dislike=True,
                like=False
            )
            rating.like = True
            rating.dislike = False
            rating.save()
            update_book_rating(book)
            return HttpResponse('')
        except Rating.DoesNotExist:
            try:
                rating = Rating.objects.get(
                    user=user,
                    book=book,
                    like=True
                )
                update_book_rating(book)
                return HttpResponse('')
            except Rating.DoesNotExist:
                Rating.objects.create(
                    user=user,
                    book=book,
                    like=True,
                    dislike=False
                )
                update_book_rating(book)
                return HttpResponse('')


def vote_minus(request, book_id):
    if request.is_ajax() and request.method == 'POST':
        book = get_object_or_404(Book, pk=book_id)
        user = request.user
        response_data = {}
        try:
            rating = Rating.objects.get(
                user=user,
                book=book,
                like=True,
                dislike=False
            )
            rating.like = False
            rating.dislike = True
            rating.save()
            update_book_rating(book)
            return HttpResponse('')
        except Rating.DoesNotExist:
            try:
                rating = Rating.objects.get(
                    user=user,
                    book=book,
                    dislike=True,
                    like=False
                )
                update_book_rating(book)
                return HttpResponse('')
            except Rating.DoesNotExist:
                Rating.objects.create(
                    user=user,
                    book=book,
                    like=False,
                    dislike=True
                )
                response_data = 'success'
                update_book_rating(book)
                return HttpResponse('')


def search(request):
    query = request.POST['query']
    try:
        books = Book.objects.filter(Q(book_title__icontains=query) | Q(book_author__name__icontains=query) | Q(
            book_category__category_name__icontains=query))
    except Book.DoesNotExist:
        books = None
    context = {
        'books': books,
        'query': query,
    }
    return render(request, 'books/search_query.html', context)


def category(request, category_id):
    return HttpResponse("Kategoria: %s" % category_id)


def update_book_rating(book):
    try:
        likes = Rating.objects.filter(like=True, book=book).count()
        print("lajki: %s " % likes)
    except Rating.DoesNotExist:
        likes = 0
    try:
        dislikes = Rating.objects.filter(dislike=True, book=book).count()
    except Rating.DoesNotExist:
        dislikes = 0
    rating = (likes / (likes + dislikes)) * 100
    book.book_rate = int(rating)
    book.save()

books/templates/books/index.html
{% extends "books/template.html" %}
{% block books_active %} active {% endblock %}
{% block content %}
     <div class="container">
         <br>
        {% if books %}
            <div class="row row-cols-1 row-cols-md-3">
            {% for book in books %}
            <div class="col mb-4">
                        <div class="card">
                            <img src="{{ book.book_img.url }}" width="{{ book.book_img.width }}" class="card-img-top" alt="Okładka">
                            <div class="card-body ">
                                <h1 class="card-title text-center"><a href="{% url 'books:book' book.id %}">{{ book.book_title }}</a></h1>
                                <hr>
                                <h6>Kategoria: <a href="{% url 'books:book_category' book.id %}">{{ book.book_category.category_name }} </a></h6>
                                {% if book.book_author.count == 1 %}
                                            <h6>Autor: {% for author in book.book_author.all %}<a href="{% url 'books:book_author' author.id %}">{{ author.name }}</a> {% endfor %}</h6>
                                          {% else %}
                                            <h6>Autorzy:{% for author in book.book_author.all %}{% if not forloop.first %},{% endif %} <a href="{% url 'books:book_author' author.id %}">{{author.name}}</a>{% endfor %}</h6>
                                      {% endif %}
                                <p class="card-text">{{ book.book_desc|truncatewords:50 }} </p>
                                <p class="text-center"><a href="{% url 'books:book' book.id %}">Czytaj dalej</a>  </p>
                            </div>
                            <div class="card-footer">
                                        <p class="text-center font-weight-bold" style="padding: 0 !important; margin: 0 !important; font-size: 100%;">
                                            {% if book.book_rate or book.book_rate == 0 %}
                                                Spodobała się <span class="{% if book.book_rate > 50 %} text-success {% else %} text-danger {% endif %}">{{ book.book_rate }}%</span> czytelników
                                            {% else %}
                                                Brak ocen
                                            {% endif %}
                                        </p>
                            </div>
                        </div>

            </div>
            {% endfor %}
            </div>
        </div>


{% else %}
    <h1 class="color-danger">Brak książek</h1>
{% endif %}
{% endblock %}

books/templates/books/search_query.html
{% extends "books/template.html" %}
{% block content %}
    <h1 style="padding: 2%">Szukana fraza: <b>{{ query }}</b> <span style="font-size: 50%">({{ books.distinct.count }} {% if books.count == 0 %}wyników{% elif books.count == 1 %}wynik{% else %}wyniki{% endif %} )</span></h1>
     <div class="container">
         <br>
        {% if books %}
            <div class="row row-cols-1 row-cols-md-3">
            {% for book in books.distinct %}
            <div class="col mb-4">
                        <div class="card">
                            <img src="{{ book.book_img.url }}" width="{{ book.book_img.width }}" class="card-img-top" alt="Okładka">
                            <div class="card-body ">
                                <h1 class="card-title text-center"><a href="{% url 'books:book' book.id %}">{{ book.book_title }}</a></h1>
                                <hr>
                                <h6>Kategoria: <a href="{% url 'books:book_category' book.id %}">{{ book.book_category.category_name }} </a></h6>
                                {% if book.book_author.count == 1 %}
                                            <h6>Autor: {% for author in book.book_author.all %}<a href="{% url 'books:book_author' book.id %}">{{ author.name }}</a> {% endfor %}</h6>
                                          {% else %}
                                            <h6>Autorzy:{% for author in book.book_author.all %}{% if not forloop.first %},{% endif %} <a href="{% url 'books:book_author' book.id %}">{{author.name}}</a>{% endfor %}</h6>
                                      {% endif %}
                              <p class="card-text">{{ book.book_desc|truncatewords:50 }}</p>
                            </div>
                            <div class="card-footer">
                                {% if book.book_likes > 0 %}
                                    <small class="text-success"><b>Ilość plusów: {{ book.book_likes }}</b></small>
                                {% else %}
                                    <small class="text-danger"><b>Ilość plusów: {{ book.book_likes }}</b></small>
                                {% endif %}
                            </div>
                        </div>

            </div>
            {% endfor %}
            </div>
        </div>


{% else %}
    <h1 class="color-danger">Brak książek</h1>
{% endif %}
{% endblock %}

books/templates/books/template.html
<!doctype html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="shortcut icon" href="/media/Book.ico"/>
    {% if title %}
        <title>{{ title }} - BookWeb</title>
    {% else %}
        <title>BookWeb</title>
    {% endif %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body style="background: #e9ecef">

{#<div class="loader-wrapper">#}
{#    <span class="loader"><span></span></span>#}
{#</div>#}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">BookWeb</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link {% block books_active %} {% endblock %}" href="{% url 'books:index' %}">Książki</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% block authors_active %} {% endblock %}"
                   href="{% url 'books:authors' %}">Autorzy</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Moje konto
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <div class="card" style="width: 18rem; margin: 0 auto; border: none">
                        <div class="card-body">
                            {% if error %}
                                <h1>Błąd</h1>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <h5 class="card-title">Witaj <b>{{ user.username }}</b>!</h5>
                                <hr>
                                <p><a href="{% url 'admin:index' %}">Panel administratora</a></p>
                                <a href="">Moje konto</a>
                                </div>
                                <div class="dropdown-divider"></div>
                                <form id="logout">
                                    <button type="submit" class="dropdown-item" href="{% url 'books:logout' %}">Wyloguj
                                        się
                                    </button>
                                </form>
                                </div>
                            {% elif not user.is_authenticated %}
                                <div class="login">
                                    <h5 class="card-title">Zaloguj się</h5>

                                    <form id="login" style="padding: 5%; width: 100%;">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="username">Nazwa użytkownika</label>
                                            <input type="text" class="form-control" id="username">
                                        </div>
                                        <div class="form-group">
                                            <label for="password">Hasło</label>
                                            <input type="password" class="form-control" id="password">

                                        </div>
                                        <p id="errorText" class="text-danger text-center">Niepoprawna nazwa użtykownika
                                            lub
                                            hasło</p>
                                        <button type="submit" class="btn btn-primary text-center">Zaloguj się</button>
                                    </form>
                                </div>
                                <div class="register">
                                    <h5 class="card-title">Zajerestruj się</h5>

                                    <form id="register" style="padding: 5%; width: 100%;">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="username_reg">Nazwa użytkownika</label>
                                            <input required type="text" class="form-control" id="username_reg">
                                        </div>
                                        <div class="form-group">
                                            <label for="email_reg">Adres e-mail</label>
                                            <input required type="email" class="form-control" id="email_reg"
                                                   aria-describedby="emailHelp">
                                        </div>
                                        <div class="form-group">
                                            <label for="password_reg">Hasło</label>
                                            <input required type="password" class="form-control" id="password_reg">
                                        </div>
                                        <div class="form-group">
                                            <label for="password_repeat">Powtórz hasło</label>
                                            <input required type="password" class="form-control" id="password_repeat">
                                        </div>
                                        <div class="form-group form-check">
                                            <input required type="checkbox" class="form-check-input" id="rules">
                                            <label class="form-check-label" for="rules">Akceptuję <a href="#">regulamin</a></label>
                                        </div>
                                        <p id="errorPasswordText" class="text-danger text-center">Podane hasła nie
                                            zgadzają się</p>
                                        <p id="username_exist" class="text-danger text-center">Użytkownik o takiej
                                            nazwie już istnieje</p>
                                        <p id="email_exist" class="text-danger text-center">Email jest już zajęty</p>
                                        <button type="submit" class="btn btn-primary text-center">Zajerestruj się
                                        </button>
                                    </form>
                                </div>
                                </div>
                                <div class="dropdown-divider"></div>
                                <a id="register_button" style="cursor: pointer;" class="dropdown-item">Zajerestruj
                                    się</a>
                                </div>
                            {% endif %}
    </div>
    </li>
    </ul>
    {% if error_message %}
        <p>{{ error_message }}</p>
    {% endif %}
    <form method="post" action="{% url 'books:search' %}" class="form-inline my-2 my-lg-0">
        {% csrf_token %}
        <input name="query" class="form-control mr-sm-2" type="search" placeholder="Szukana fraza"
               aria-label="Search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Szukaj</button>
    </form>
    </div>
</nav>

{% block content %}

{% endblock %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% block scripts %}

{% endblock %}
{#<script type="text/javascript">#}
{#    $(window).on('load', function () {#}
{#        $('.loader-wrapper').fadeOut("slow");#}
{#    })#}
{#</script>#}
<script type="text/javascript">

    hidden = [
        '#errorText',
        '.register',
        '#errorPasswordText',
        '#username_exist',
        '#email_exist'
    ];

    $('.dropdown-menu').on('click', function (e) {
        e.stopPropagation();
    });

    $(window).on('load', function () {
        for (i in hidden) {
            $(hidden[i]).fadeOut();
        }
    });

    $('#register_button').click(function (e) {
        $('.register').slideToggle();
        $('.login').slideToggle();
        if ($(this).text() === "Zaloguj się") {
            $('#register_button').html("Zajerestruj się");
        } else {
            $('#register_button').html("Zaloguj się");
        }
    });


    $(document).on('submit', '#login', function (e) {
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url 'books:login' %}',
            data: {
                username: $('#username').val(),
                password: $('#password').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (response) {
                if (response['result'] === 'success') {
                    location.reload();
                } else {
                    $('#errorText').fadeIn("slow");
                }
            },
        });

    });

    $(document).on('submit', '#register', function (e) {
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url 'books:register_user' %}',
            data: {
                username: $('#username_reg').val(),
                password: $('#password_reg').val(),
                password_repeat: $('#password_repeat').val(),
                email: $('#email_reg').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function (response) {
                switch (response['result']) {
                    case 'success':
                        location.reload();
                        break;
                    case 'failed':
                        $('#username_exist').fadeOut();
                        $('#email_exist').fadeOut();
                        $('#errorPasswordText').fadeIn("slow");
                        break;
                    case 'username_exist':
                        $('#errorPasswordText').fadeOut();
                        $('#email_exist').fadeOut();
                        $('#username_exist').fadeIn("slow");
                        break;
                    case 'email_exist':
                        $('#username_exist').fadeOut();
                        $('#errorPasswordText').fadeOut();
                        $('#email_exist').fadeIn("slow");
                        break;
                }
            },
        });

    });

    $(document).on('submit', '#logout', function (e) {
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url 'books:logout' %}',
            data: {
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
            },
            success: function () {
                location.reload();
            },
        });

    });
</script>
</body>
</html>